/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as RoutesIdRouteImport } from './routes/routes.$id'
import { Route as RidesIdRouteImport } from './routes/rides.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as InvoicePublicTokenRouteImport } from './routes/invoice.public.$token'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIdRoute = RoutesIdRouteImport.update({
  id: '/routes/$id',
  path: '/routes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIdRoute = RidesIdRouteImport.update({
  id: '/rides/$id',
  path: '/rides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicePublicTokenRoute = InvoicePublicTokenRouteImport.update({
  id: '/invoice/public/$token',
  path: '/invoice/public/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/drivers': typeof DriversRoute
  '/login': typeof LoginRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/invoice/public/$token': typeof InvoicePublicTokenRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/drivers': typeof DriversRoute
  '/login': typeof LoginRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/invoices': typeof InvoicesIndexRoute
  '/routes': typeof RoutesIndexRoute
  '/invoice/public/$token': typeof InvoicePublicTokenRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/driver': typeof DriverRoute
  '/drivers': typeof DriversRoute
  '/login': typeof LoginRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/routes/$id': typeof RoutesIdRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/routes/': typeof RoutesIndexRoute
  '/invoice/public/$token': typeof InvoicePublicTokenRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/driver'
    | '/drivers'
    | '/login'
    | '/invoices/$id'
    | '/rides/$id'
    | '/routes/$id'
    | '/invoices/'
    | '/routes/'
    | '/invoice/public/$token'
    | '/api/public/hooks/process-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/driver'
    | '/drivers'
    | '/login'
    | '/invoices/$id'
    | '/rides/$id'
    | '/routes/$id'
    | '/invoices'
    | '/routes'
    | '/invoice/public/$token'
    | '/api/public/hooks/process-reminders'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/dashboard'
    | '/driver'
    | '/drivers'
    | '/login'
    | '/invoices/$id'
    | '/rides/$id'
    | '/routes/$id'
    | '/invoices/'
    | '/routes/'
    | '/invoice/public/$token'
    | '/api/public/hooks/process-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  DriverRoute: typeof DriverRoute
  DriversRoute: typeof DriversRoute
  LoginRoute: typeof LoginRoute
  InvoicesIdRoute: typeof InvoicesIdRoute
  RidesIdRoute: typeof RidesIdRoute
  RoutesIdRoute: typeof RoutesIdRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
  InvoicePublicTokenRoute: typeof InvoicePublicTokenRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$id': {
      id: '/routes/$id'
      path: '/routes/$id'
      fullPath: '/routes/$id'
      preLoaderRoute: typeof RoutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$id': {
      id: '/rides/$id'
      path: '/rides/$id'
      fullPath: '/rides/$id'
      preLoaderRoute: typeof RidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/public/$token': {
      id: '/invoice/public/$token'
      path: '/invoice/public/$token'
      fullPath: '/invoice/public/$token'
      preLoaderRoute: typeof InvoicePublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  DriverRoute: DriverRoute,
  DriversRoute: DriversRoute,
  LoginRoute: LoginRoute,
  InvoicesIdRoute: InvoicesIdRoute,
  RidesIdRoute: RidesIdRoute,
  RoutesIdRoute: RoutesIdRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
  InvoicePublicTokenRoute: InvoicePublicTokenRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
